#!/usr/bin/env bash

THEME_NAME="canopy"

# Base
THEME_BASE_BG="#16231C"
THEME_BASE_FG="#D8E6DC"

# Accent
THEME_ACCENT_BG="#3FAE6A"
THEME_ACCENT_FG="#102018"

# Status
THEME_STATUS_BG="#101A14"
THEME_STATUS_FG="#D8E6DC"

# Session indicator
THEME_SESSION_BG="#A3BE8C"
THEME_SESSION_FG="$THEME_ACCENT_FG"

# Windows
THEME_WINDOW_BG="#26382D"
THEME_WINDOW_FG="#D8E6DC"

# Selected window
THEME_WINDOW_CURRENT_BG="$THEME_ACCENT_BG"
THEME_WINDOW_CURRENT_FG="$THEME_ACCENT_FG"

# Pane borders
THEME_PANE_BORDER="#B8C9BE"
THEME_PANE_ACTIVE_BORDER="$THEME_ACCENT_BG"

# Modules
THEME_MODULE_BG="#26382D"
THEME_MODULE_FG="#D8E6DC"

# Modes
THEME_MODE_NORMAL_BG="$THEME_ACCENT_BG"
THEME_MODE_COMMAND_BG="#D6A94A"
THEME_MODE_COPY_BG="#C65F58"
THEME_MODE_OTHER_BG="#9A7BB8"

THEME_MODE_FG="$THEME_ACCENT_FG"
