#!/usr/bin/env bash

THEME_NAME="dune"

# Base
THEME_BASE_BG="#241A14"
THEME_BASE_FG="#E8DCC4"

# Accent
THEME_ACCENT_BG="#C9963E"
THEME_ACCENT_FG="#241A14"

# Status
THEME_STATUS_BG="#241A14"
THEME_STATUS_FG="#E8DCC4"

# Session indicator
THEME_SESSION_BG="#EBCB8B"
THEME_SESSION_FG="$THEME_ACCENT_FG"

# Windows
THEME_WINDOW_BG="#493528"
THEME_WINDOW_FG="#F3E5C8"

# Selected window
THEME_WINDOW_CURRENT_BG="$THEME_ACCENT_BG"
THEME_WINDOW_CURRENT_FG="$THEME_ACCENT_FG"

# Pane borders
THEME_PANE_BORDER="#D8DEE9"
THEME_PANE_ACTIVE_BORDER="$THEME_ACCENT_BG"

# Modules
THEME_MODULE_BG="$THEME_WINDOW_BG"
THEME_MODULE_FG="$THEME_WINDOW_FG"

# Modes
THEME_MODE_NORMAL_BG="$THEME_ACCENT_BG"
THEME_MODE_COMMAND_BG="#5FA89B"
THEME_MODE_COPY_BG="#B85C4B"
THEME_MODE_OTHER_BG="#8B6F8F"

THEME_MODE_FG="$THEME_ACCENT_FG"
