#!/usr/bin/env bash

# =========================
# Dune color palette
# =========================

THEME_NAME="dune"

# Base
THEME_BASE_BG="#241A14"
THEME_BASE_FG="#E8DCC4"

# Accent
THEME_ACCENT_BG="#C9963E"
THEME_ACCENT_FG="#241A14"

# Status
THEME_STATUS_BG="#1B1410"
THEME_STATUS_FG="#E8DCC4"

# Session indicator
THEME_SESSION_BG="#EBCB8B"
THEME_SESSION_FG="$THEME_ACCENT_FG"

# Windows
THEME_WINDOW_BG="#493528"
THEME_WINDOW_FG="#F3E5C8"

# Selected window
THEME_WINDOW_CURRENT_BG="$THEME_ACCENT_BG"
THEME_WINDOW_CURRENT_FG="$THEME_ACCENT_FG"

# Pane borders
THEME_PANE_BORDER="#D8DEE9"
THEME_PANE_ACTIVE_BORDER="$THEME_ACCENT_BG"

# Modules
THEME_MODULE_BG="$THEME_WINDOW_BG"
THEME_MODULE_FG="$THEME_WINDOW_FG"

# Modes
THEME_MODE_NORMAL_BG="$THEME_ACCENT_BG"
THEME_MODE_COMMAND_BG="#5FA89B"
THEME_MODE_COPY_BG="#B85C4B"
THEME_MODE_OTHER_BG="#8B6F8F"

THEME_MODE_FG="$THEME_ACCENT_FG"

# =========================
# Dune terminal color palette
# =========================

THEME_FG="#E8DCC4"
THEME_BG="#241A14"
THEME_CURSOR="$THEME_ACCENT_BG"

# ANSI colors
THEME_COLOR_0="#241A14"
THEME_COLOR_1="#B85C4B"
THEME_COLOR_2="#7F9B62"
THEME_COLOR_3="#C9963E"
THEME_COLOR_4="#9A7B5A"
THEME_COLOR_5="#8B6F8F"
THEME_COLOR_6="#5FA89B"
THEME_COLOR_7="#E8DCC4"

THEME_COLOR_8="#493528"
THEME_COLOR_9="#C96F5D"
THEME_COLOR_10="#9AAF78"
THEME_COLOR_11="#EBCB8B"
THEME_COLOR_12="#C4A77D"
THEME_COLOR_13="#A68EAA"
THEME_COLOR_14="#7FC3B5"
THEME_COLOR_15="#F3E5C8"
