#!/usr/bin/env bash

# =========================
# Nord color palette
# =========================

THEME_NAME="nord"

# Base
THEME_BASE_BG="#2E3440"
THEME_BASE_FG="#D8DEE9"

# Accent
THEME_ACCENT_BG="#88C0D0"
THEME_ACCENT_FG="#2E3440"

# Status
THEME_STATUS_BG="#242933"
THEME_STATUS_FG="#D8DEE9"

# Session indicator
THEME_SESSION_BG="#81A1C1"
THEME_SESSION_FG="$THEME_ACCENT_FG"

# Windows
THEME_WINDOW_BG="#3B4252"
THEME_WINDOW_FG="#D8DEE9"

# Selected window
THEME_WINDOW_CURRENT_BG="$THEME_ACCENT_BG"
THEME_WINDOW_CURRENT_FG="$THEME_ACCENT_FG"

# Pane borders
THEME_PANE_BORDER="#4C566A"
THEME_PANE_ACTIVE_BORDER="$THEME_ACCENT_BG"

# Modules
THEME_MODULE_BG="$THEME_WINDOW_BG"
THEME_MODULE_FG="$THEME_WINDOW_FG"

# Modes
THEME_MODE_NORMAL_BG="$THEME_ACCENT_BG"
THEME_MODE_COMMAND_BG="#EBCB8B"
THEME_MODE_COPY_BG="#BF616A"
THEME_MODE_OTHER_BG="#B48EAD"

THEME_MODE_FG="$THEME_ACCENT_FG"

# =========================
# Nord terminal color palette
# =========================

THEME_FG="#D8DEE9"
THEME_BG="#2E3440"
THEME_CURSOR="$THEME_ACCENT_BG"

# ANSI colors
THEME_COLOR_0="#3B4252"
THEME_COLOR_1="#BF616A"
THEME_COLOR_2="#A3BE8C"
THEME_COLOR_3="#EBCB8B"
THEME_COLOR_4="#81A1C1"
THEME_COLOR_5="#B48EAD"
THEME_COLOR_6="#88C0D0"
THEME_COLOR_7="#E5E9F0"

THEME_COLOR_8="#4C566A"
THEME_COLOR_9="#BF616A"
THEME_COLOR_10="#A3BE8C"
THEME_COLOR_11="#EBCB8B"
THEME_COLOR_12="#81A1C1"
THEME_COLOR_13="#B48EAD"
THEME_COLOR_14="#8FBCBB"
THEME_COLOR_15="#ECEFF4"
