#!/usr/bin/env bash

THEME_NAME="nord"

# Base
THEME_BASE_BG="#2E3440"
THEME_BASE_FG="#D8DEE9"

# Accent
THEME_ACCENT_BG="#88C0D0"
THEME_ACCENT_FG="#2E3440"

# Status
THEME_STATUS_BG="#242933"
THEME_STATUS_FG="#D8DEE9"

# Session indicator
THEME_SESSION_BG="#81A1C1"
THEME_SESSION_FG="$THEME_ACCENT_FG"

# Windows
THEME_WINDOW_BG="#3B4252"
THEME_WINDOW_FG="#D8DEE9"

# Selected window
THEME_WINDOW_CURRENT_BG="$THEME_ACCENT_BG"
THEME_WINDOW_CURRENT_FG="$THEME_ACCENT_FG"

# Pane borders
THEME_PANE_BORDER="#4C566A"
THEME_PANE_ACTIVE_BORDER="$THEME_ACCENT_BG"

# Modules
THEME_MODULE_BG="#3B4252"
THEME_MODULE_FG="#ECEFF4"

# Modes
THEME_MODE_NORMAL_BG="$THEME_ACCENT_BG"
THEME_MODE_COMMAND_BG="#EBCB8B"
THEME_MODE_COPY_BG="#BF616A"
THEME_MODE_OTHER_BG="#B48EAD"

THEME_MODE_FG="$THEME_ACCENT_FG"
